export const timeZone = {
    "Etc/GMT+12": "GMT -12:00 Dateline",
    "Pacific/Midway": "GMT -11:00 Samoa",
    "America/Adak": "GMT -10:00 Adak",
    "Pacific/Honolulu": "GMT -10:00 Hawaii",
    "Pacific/Marquesas": "GMT -09:30 Marquesas",
    "America/Anchorage": "GMT -09:00 Alaska",
    "America/Los_Angeles": "GMT -08:00 US/Canada Pacific",
    "America/Tijuana": "GMT -08:00 Baja California",
    "America/Chihuahua": "GMT -07:00 Chihuahua, La Paz, Mazatlan",
    "America/Denver": "GMT -07:00 US/Canada Mountain",
    "America/Fort_Nelson": "GMT -07:00 Fort Nelson",
    "America/Phoenix": "GMT -07:00 Arizona",
    "America/Chicago": "GMT -06:00 US/Canada Central",
    "America/Guatemala": "GMT -06:00 Central America",
    "America/Mexico_City": "GMT -06:00 Guadalajara, Mexico City, Monterrey",
    "America/Regina": "GMT -06:00 Saskatchewan",
    "Pacific/Easter": "GMT -06:00 Easter",
    "America/Bogota": "GMT -05:00 Colombia",
    "America/Cancun": "GMT -05:00 Cancun, Chetumal",
    "America/Havana": "GMT -05:00 Havana",
    "America/Indiana/Indianapolis": "GMT -05:00 Indiana (East)",
    "America/New_York": "GMT -05:00 US/Canada Eastern",
    "America/Port-au-Prince": "GMT -05:00 Port-au-Prince",
    "America/Asuncion": "GMT -04:00 Asuncion",
    "America/Caracas": "GMT -04:00 Caracas",
    "America/Cuiaba": "GMT -04:00 Cuiaba",
    "America/Grand_Turk": "GMT -04:00 Turks and Caicos Islands",
    "America/Guyana": "GMT -04:00 Georgetown, La Paz, Manaus, San Juan",
    "America/Halifax": "GMT -04:00 Atlantic Time (Canada)",
    "America/Santiago": "GMT -04:00 Pacific South America",
    "America/St_Johns": "GMT -03:30 Newfoundland",
    "America/Araguaina": "GMT -03:00 Araguaina",
    "America/Argentina/Buenos_Aires": "GMT -03:00 Argentina",
    "America/Bahia": "GMT -03:00 Salvador",
    "America/Cayenne": "GMT -03:00 Cayenne, Fortaleza",
    "America/Godthab": "GMT -03:00 Greenland",
    "America/Miquelon": "GMT -03:00 Miquelon",
    "America/Montevideo": "GMT -03:00 Montevideo",
    "America/Punta_Arenas": "GMT -03:00 Punta_Arenas",
    "America/Sao_Paulo": "GMT -03:00 Brasilia",
    "Atlantic/South_Georgia": "GMT -02:00 Mid-Atlantic",
    "Atlantic/Azores": "GMT -01:00 Azores",
    "Atlantic/Cape_Verde": "GMT -01:00 Cape Verde Is.",
    "Africa/Casablanca": "GMT +00:00 Casablanca",
    "Africa/Monrovia": "GMT +00:00 Monrovia",
    "Europe/London": "GMT +00:00 Britain, Ireland, Portugal",
    "UTC": "GMT/UTC Coordinated Universal Time",
    "Africa/Algiers": "GMT +01:00 West Central Africa",
    "Africa/Windhoek": "GMT +01:00 Namibia",
    "Europe/Belgrade": "GMT +01:00 Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "Europe/Berlin": "GMT +01:00 Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "Europe/Brussels": "GMT +01:00 Brussels, Copenhagen, Madrid, Paris",
    "Europe/Warsaw": "GMT +01:00 Sarajevo, Skopje, Warsaw, Zagreb",
    "Africa/Cairo": "GMT +02:00 Egypt",
    "Africa/Harare": "GMT +02:00 Harare, Pretoria",
    "Africa/Tripoli": "GMT +02:00 Tripoli",
    "Asia/Amman": "GMT +02:00 Jordan",
    "Asia/Beirut": "GMT +02:00 Beirut",
    "Asia/Damascus": "GMT +02:00 Damascus",
    "Asia/Gaza": "GMT +02:00 Gaza",
    "Asia/Jerusalem": "GMT +02:00 Jerusalem",
    "Europe/Athens": "GMT +02:00 Athens, Beirut, Bucharest, Istanbul",
    "Europe/Bucharest": "GMT +02:00 Bucharest",
    "Europe/Chisinau": "GMT +02:00 Chisinau",
    "Europe/Helsinki": "GMT +02:00 Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    "Europe/Kaliningrad": "GMT +02:00 Kaliningrad (RTZ 1)",
    "Africa/Nairobi": "GMT +03:00 Nairobi",
    "Asia/Baghdad": "GMT +03:00 Iraq",
    "Asia/Kuwait": "GMT +03:00 Kuwait, Riyadh",
    "Europe/Istanbul": "GMT +03:00 Istanbul",
    "Europe/Minsk": "GMT +03:00 Minsk",
    "Europe/Moscow": "GMT +03:00 Moscow, St. Petersburg, Volgograd (RTZ 2)",
    "Asia/Tehran": "GMT +03:30 Tehran",
    "Asia/Baku": "GMT +04:00 Baku",
    "Asia/Muscat": "GMT +04:00 Abu Dhabi, Muscat",
    "Asia/Tbilisi": "GMT +04:00 Tbilisi",
    "Asia/Yerevan": "GMT +04:00 Yerevan",
    "Europe/Astrakhan": "GMT +04:00 Astrakhan",
    "Europe/Samara": "GMT +04:00 Izhevsk, Samara (RTZ 3)",
    "Europe/Saratov": "GMT +04:00 Saratov",
    "Indian/Mauritius": "GMT +04:00 Port Louis",
    "Asia/Kabul": "GMT +04:30 Kabul",
    "Asia/Karachi": "GMT +05:00 Islamabad, Karachi",
    "Asia/Tashkent": "GMT +05:00 Tashkent",
    "Asia/Yekaterinburg": "GMT +05:00 Ekaterinburg (RTZ 4)",
    "Asia/Colombo": "GMT +05:30 Sri Jayawardenepura Kotte",
    "Asia/Kolkata": "GMT +05:30 Chennai, Kolkata, Mumbai, New Delhi",
    "Asia/Kathmandu": "GMT +05:45 Kathmandu",
    "Asia/Almaty": "GMT +06:00 Astana",
    "Asia/Dhaka": "GMT +06:00 Dhaka",
    "Asia/Omsk": "GMT +06:00 Omsk",
    "Asia/Yangon": "GMT +06:30 Yangon",
    "Asia/Bangkok": "GMT +07:00 Bangkok, Hanoi, Jakarta",
    "Asia/Barnaul": "GMT +07:00 Barnaul",
    "Asia/Hovd": "GMT +07:00 Hovd",
    "Asia/Krasnoyarsk": "GMT +07:00 Krasnoyarsk (RTZ 6)",
    "Asia/Novosibirsk": "GMT +07:00 Novosibirsk (RTZ 5)",
    "Asia/Tomsk": "GMT +07:00 Tomsk",
    "Asia/Hong_Kong": "GMT +08:00 Beijing, Chongqing, Hong Kong, Urumqi",
    "Asia/Irkutsk": "GMT +08:00 Irkutsk (RTZ 7)",
    "Asia/Kuala_Lumpur": "GMT +08:00 Kuala Lumpur",
    "Asia/Singapore": "GMT +08:00 Singapore",
    "Asia/Taipei": "GMT +08:00 Taipei",
    "Asia/Ulaanbaatar": "GMT +08:00 Ulaanbaatar",
    "Australia/Perth": "GMT +08:00 Perth",
    "Asia/Pyongyang": "GMT +08:30 Pyongyang",
    "Australia/Eucla": "GMT +08:45 Eucla",
    "Asia/Chita": "GMT +09:00 Chita",
    "Asia/Seoul": "GMT +09:00 Korea",
    "Asia/Tokyo": "GMT +09:00 Japan",
    "Asia/Yakutsk": "GMT +09:00 Yakutsk (RTZ 8)",
    "Australia/Adelaide": "GMT +09:30 Adelaide",
    "Australia/Darwin": "GMT +09:30 Darwin",
    "Asia/Vladivostok": "GMT +10:00 Vladivostok, Magadan (RTZ 9)",
    "Australia/Brisbane": "GMT +10:00 Brisbane",
    "Australia/Hobart": "GMT +10:00 Hobart",
    "Australia/Sydney": "GMT +10:00 Canberra, Melbourne, Sydney",
    "Pacific/Guam": "GMT +10:00 Guam, Port Moresby",
    "Australia/Lord_Howe": "GMT +10:30 Lord_Howe",
    "Asia/Magadan": "GMT +11:00 Magadan",
    "Asia/Sakhalin": "GMT +11:00 Sakhalin",
    "Asia/Srednekolymsk": "GMT +11:00 Chokurdakh (RTZ 10)",
    "Pacific/Bougainville": "GMT +11:00 Bougainville Standard Time",
    "Pacific/Guadalcanal": "GMT +11:00 Solomon Is. / New Caledonia",
    "Pacific/Norfolk": "GMT +11:00 Norfolk",
    "Asia/Kamchatka": "GMT +12:00 Anadyr, Petropavlovsk-Kamchatsky (RTZ 11)",
    "Pacific/Auckland": "GMT +12:00 New Zealand",
    "Pacific/Fiji": "GMT +12:00 Fiji",
    "Pacific/Chatham": "GMT +12:45 Chatham",
    "Pacific/Apia": "GMT +13:00 Samoa",
    "Pacific/Tongatapu": "GMT +13:00 Nuku’alofa",
    "Pacific/Kiritimati": "GMT +14:00 Kiritimati Island",
};